### PR TITLE
Finish the outdated gem upgrades

### PR DESCRIPTION
**Pull request by acant**
Only the rugged upgrade required significant code changes.

### CODE REVIEW

**Comment by acant** [comment]
Ah, so close. Appears that has changed about how Rugged::Config.global works. Investigating and hopefully I will have a fix soon.

**Comment by nesquena** [comment]
Ok great, thanks

**Comment by acant** [comment]
Hey, it actually passed! :smiley: 
@nesquena This is ready to merge, with all the necessary changes to account for the update rugged API.

**Comment by nesquena** [comment]
Nice!

**Pull request merged**
