### PR TITLE
Seperate integration tests and disable UI tests on Travis

### PR DESCRIPTION
**Pull request by acant**
The UI tests seem to be so unreliable on Travis, and they get run locally, that I want to try disabling them.

### CODE REVIEW

**Comment by acant** [comment]
@nesquena This is ready to merge, if you are comfortable with limiting the execution of the UI tests, I think it will make the CI tests execution more reliable.

**Comment by nesquena** [comment]
Thanks for reconfiguring this! Nice to see travis-ci green again even if it means having to skip running the UI tests.

**Comment by acant** [comment]
I just re-ran the tests on master and now it is actually green. Ruby1.9 seems to just intermittently fail.
I'm thinking that I'll put 1.9 into the 'allowed_failures' section in my next PR. It is out of support, so hopefully will be little used anyways.
BTW @nesquena if you have a moment to generate an API token for CodeClimate then we can also get their code coverage tool running. The token just needs to be added to .travis.yml at this location:
```
addons:
  code_climate:
    repo_token: adf08323...
```
And then the [codeclimate-test-reporter gem](https://rubygems.org/gems/codeclimate-test-reporter) should start reporting.
(P.S.: Details about this configuration are [here](https://docs.travis-ci.com/user/code-climate/#Ruby)).

**Comment by nesquena** [comment]
@acant Thanks, added here 3a147b8099e50c5a14adb9fe00c6f2530cf9e592

**Pull request merged**
