### PR TITLE
Doing some pre-Celluloid cleanup

### PR DESCRIPTION
**Pull request by acant**
So the Celluloid conversion branch is getting failures on TravisCI, and I would like to isolate that from the various refactoring and cleanups that I have done in order to make that conversion easier. 
This PR is going to get a bunch of those commits cherry picked out of #113 and should get merged into master first.

### CODE REVIEW

**Comment by acant** [comment]
@nesquena Test are finally passing! At least for some pre-Celluloid refactoring.
I do need some assistances before this is ready to merge.

I have swapped Coveralls with the CodeClimate coverage tool, because Coveralls appears to have a conflict with Ruby1.9.3 and was preventing TravisCI from running those tests. But in order make that report data correctly the TravisCI environment needs to set a CodeClimate repo token. I think that only you can get this from the setup tab for the repo on CodeClimate.

If you can get this token then I will add it to the .travis.yml.

**Comment by acant** [comment]
Woohoo! I think I have got all the refactoring commits in, and the tests are passing.
Once the CodeClimate token is added then this is ready to merge, and then I'll continue with the rest of the Celluloid conversion.

**Comment by acant** [comment]
I have removed  the Celluloid changes, again, because they seem to have the same problems as the other branch. (Unexpected Actor crashes)  I have some more clean up, and testing to do and then I will try again.

**Comment by nesquena** [comment]
Thanks for the update

**Comment by acant** [comment]
Hi @nesquena, I have been busy with other things and have not made any more progress with the Celulloid conversion. It seems like I will need to improve the logging/error reporting in order to figure out what is going wrong.

However, I think that the existing refactorings are good to merge. I have been running them for the last several days and everything seems to be working fine.
After the merge, the .travis.yml also needs to have the CodeClimate token added, to enable the code coverage collection though CodeClimate:
```
addons:
  code_climate:
    repo_token: <TOKEN_VALUE>
```
It appears that only the owner of the repository can generate this token.

If you have any concerns please let me know, and I will try to address them. This has all be hanging in a branch way to long, so I would really like to get this merged.

**Comment by nesquena** [comment]
Ok, will merge then now. Thanks again!

**Comment by acant** [comment]
Awesome! Thanks @nesquena.

**Pull request merged**
