### PR TITLE
Enable code fencing and syntax highlighing in Markdown

### PR DESCRIPTION
**Pull request by acant**
As the title says, and with the already include CodeRay syntax highlighter. I am also extracted the code for rendering content into a Sinatra helper. This should reduce the complexity of the BrowserApp class a little.

In the process of making these changes I also noticed a typo in the inline README code, and the non-text file display. Both of those should be fixed.

And I added an integration test for the inline README display. A TODO marker still remains for doing the same for the non-text file display.

### CODE REVIEW

**Comment by acant** [comment]
@nesquena This is ready to merge, assuming that Travis stays green. If not I'll try to fix it up tomorrow.

**Comment by nesquena** [comment]
Sweet, thanks!

**Comment by nesquena** [comment]
Hoping for the best, if travis build breaks, hopefully we can fix quickly. I'll release a new version after that.

**Comment by acant** [comment]
Thanks for merging to quickly!
 I just realized that I forgot to update the changelog, so I am going to quickly do that in master.

**Comment by nesquena** [comment]
Travis passed: https://travis-ci.org/nesquena/gitdocs. Thanks for updating changelog, than I can release. I think it's time to take it out of pre, it's been long enough ;)

**Comment by nesquena** [comment]
@acant Pushed 0.5.0 final, figured we might as well. Onto 0.6.0 :) Thanks for keeping gitdocs project alive. Look forward to your work to upgrade from eventmachine to celluloid. Thanks also for porting to sinatra from renee!

**Comment by acant** [comment]
Woohoo! Thanks for pushing out the gem update @nesquena. Nice to get to 0.6.0. Makes a good marker for the celluloid work too, since that is going to be a big change.

I am happy to be working on this project. What you had already written was a really good fit for my workflow,  and being able to contribute has only been making it better.

**Pull request merged**
