### PR TITLE
Convert the notification to use notiffany gem

### PR DESCRIPTION
**Pull request by acant**
Also going to do some refactoring and clean up in the process. Specifically I hope that I will make the integration tests faster and more reliable.

### CODE REVIEW

**Comment by nesquena** [comment]
What happened with the tests? https://travis-ci.org/nesquena/gitdocs/builds/79777537 are they just broken in general?

**Comment by acant** [comment]
Frustratingly, no. 
The tests are passing locally but failing on TravisCI. Seemingly on timing related issues. I have been playing with the timeouts and trying to simplify the test code, which hopefully will either fix the failures or reveal the problems.

If you have time, could you pull this branch and run the tests? It would give me another data point, and might help clarify if this is really specific to the TravisCI environment.

**Comment by acant** [comment]
I am uploading some temporary commits to try and gather more information about the failures on TravisCI. They will be removed before merging.
The commits are intended to display more information logging information than usual.

**Comment by nesquena** [comment]
Ok thanks for the heads up, sorry travis is giving you so much trouble.

**Comment by acant** [comment]
np. Hopefully by the time I'm finish, I'll have a better understanding of...something. :)
My worst case scenario is to just disable the failing tests in Travis, but there is already one case of that. It would be a shame to add more.

**Comment by acant** [comment]
And the test are passing! The problem was that git was not finding a user.email and user.name setting when running the integration tests in TravisCI. My wonder if the TravisCI image used to have those values set in the system config, and now it does not.
Explicitly, setting them in the test HOME directory will be generally more reliable.

@nesquena I have re-based the existing commits so they are ready to merge if you like. And I'll continue with the notification changes here or in another PR.

**Comment by nesquena** [comment]
Sweet! Great news.

**Comment by acant** [comment]
Thanks @nesquena. I just updated the README and CHANGELOG in master, so everything should be up to date now.

**Comment by nesquena** [comment]
Nice!

**Pull request merged**
